### ISSUE TITLE
Search for Subtiles only

### ISSUE THREAD

**Issue by cellx** [frankhale/toby#60]
Can this search tool find the movie with subtiles and specify language too?

**Comment by frankhale** [comment]
If the YouTube Data API exposes that then I don't see it as a problem.

**Comment by frankhale** [comment]
I'll have a look into this. Thanks for the feature suggestion.

**Comment by frankhale** [comment]
is this possible to do currently on YouTube? I mean by just typing something into their search box?

**Comment by frankhale** [comment]
Apparently at least searching for closed caption is possible on YouTube:

https://support.google.com/youtube/answer/3029103?hl=en

I don't know if their data API exposes this. I'll check.

**Comment by frankhale** [comment]
Yes the Data API exposes searching for videos with subtitle (eg. Closed Caption) but now that I read your question again I am think you want to search for some arbitrary closed caption that was displayed in the video and then find the video on YouTube.

**Comment by frankhale** [comment]
I'm using a very simple wrapper library over the YouTube Data API. It can return videos based on simple searches. I don't have plans to add complex searching at this time.
